package iabtcf

import (
	"testing"
)

// all consent strings generated by: https://iabtcf.com/#/encode
func TestParseCoreString(t *testing.T) {
	tests := []struct {
		name                       string
		c                          string
		wantPurposesAllowed        bool
		wantSpecialFeaturesAllowed bool
		wantVendorAllowed          bool
		publisherCountry           string
		wantVersion int
		wantErr                    bool
	}{
		{
			"empty",
			"",
			true,
			true,
			true,
			"AA",
			0,
			true,
		},
		{
			"v1 string #1",
			"BOv1FaTOv1FdvAHABBFRDG-AAAAvRr_7__7-_9_-_f__9uj3Or_v_f__32ccL59v_h_7v-_7fi_20nV4u_1vft9yfk1-5ctDztp507iakivXmqdeb1v_nz3_5pxP78k89r7337Ew_v8_v-b7BCON9YxEiAAA",
			false,
			false,
			false,
			"",
			1,
			true,
		},
		{
			"v1 string #2",
			"BOzZQ6oOzZQ6oAAAAAktB6-AAAAlWD8AB4ABwA_4AlgCpgHTAQuAD4AqoCKQBCAERABeAO0AYIAWACpAEGAP4ANYAXAAtwCOgDgAMMAlUAIgAYQAYAAVAOIAH8Az4ACwASACjAA2AK0BD4BrgABAE3AH6AJwANwAOQBDAAeAAkAjUAFIAogADACTAKKATUAdQAdwAegHUADmAQABB4A6wDFAIKAIUAAEAngAUQBzgBPAM0AFwAsoAlAAHgBQAQMADQAkwAzgBLgE7AJ-ARMATYACAAPgCYAGiABgAaoBgwBiAB9AAIATQAKgBSACXADZAC2AbIAGIACgAWgDuAFcABkANAB8wCqABwAL8ADMAyYApQDlAFnAC8AU0APgAIgCLADiAAcAE0AcoB5ADhAFdAC0AS0A84CBAAGgHaAISAawBDABnQAqgGNAGaAYAAfQACQAnAAqADaAd8AcYA1AAhgG7ANOAJUAKQAjgArAChANAARwBIAARQAxADCADKAEEAewB0gBwgDIAB-ADIAT4AUwB6gCMAEAAeYA34BmQBoACdAHQAagAuoAOwAGAEZAIKAYEACwBhABeAG6ADSAi8AYABbQCVAIgAHiAHEALoCSwC4gAlAAuAIkAvoBxwBVAHbAIEAfQAI4BJwAIAErAG0AWYAUgBPQD7ADyAKgAa0A9wAAwBFgC5ABAAEkAJACPADXgHqAMuAgAAnAATAC9ACPAQ6ACwA_QB1QCSgB-A",
			false,
			false,
			false,
			"",
			1,
			false,
		},
		{
			"10 purposes and 2 special features allowed, vendor allowed",
			"COwIsAvOwIsAvBIAAAENAPCMAP_AAP_AAAAAFoQBQABAAGAAQAAwACQAAAAA.IFoEUQQgAIQwgIwQABAEAAAAOIAACAIAAAAQAIAgEAACEAAAAAgAQBAAAAAAAGBAAgAAAAAAAFAAECAAAgAAQARAEQAAAAAJAAIAAgAAAYQEAAAQmAgBC3ZAYzUw",
			true,
			true,
			true,
			"AA",
			2,
			false,
		},
		{
			"only 5 purposes and 1 special feature allowed, vendor not allowed",
			"COwIsAvOwIsAvBIAAAENAPCIAPgAAP_AAAAAFoEUQQgAIQwgIwQABAEAAAAOIAACAIAAAAQAIAgEAACEAAAAAgAQBAAAAAAAGBAAgAAAAAAAFAAECAAAgAAQARAEQAAAAAJAAIAAgAAAYQEAAAQmAgBC3ZAYzUwAAAAA.IFoEUQQgAIQwgIwQABAEAAAAOIAACAIAAAAQAIAgEAACEAAAAAgAQBAAAAAAAGBAAgAAAAAAAFAAECAAAgAAQARAEQAAAAAJAAIAAgAAAYQEAAAQmAgBC3ZAYzUw",
			false,
			false,
			false,
			"AA",
			2,
			false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Arrange
			purposes := []int{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
			specialFeatures := []int{1, 2}
			vendor := 4

			// Act
			got, err := ParseCoreString(tt.c)

			// Assert
			if (err != nil) != tt.wantErr {
				t.Errorf("ParseCoreString() error = %v, wantErr %v", err, tt.wantErr)
			}
			if err != nil {
				return
			}

			if got.Version != tt.wantVersion {
				t.Errorf("Version failed. Expected %d, got %d", tt.wantVersion, got.Version)
			}

			if got.Version != 2 {
				return
			}

			if pa := got.EveryPurposeAllowed(purposes); pa != tt.wantPurposesAllowed {
				t.Errorf("EveryPurposeAllowed failed. Expected %t, got %t", tt.wantPurposesAllowed, pa)
			}
			if sfa := got.EverySpecialFeatureAllowed(specialFeatures); sfa != tt.wantSpecialFeaturesAllowed {
				t.Errorf("EverySpecialFeatureAllowed failed. Expected %t, got %t", tt.wantSpecialFeaturesAllowed, sfa)
			}
			if va := got.VendorAllowed(vendor); va != tt.wantVendorAllowed {
				t.Errorf("VendorAllowed failed. Expected %t, got %t. \nIsRangeEncoding: %t\nVendors: %#v", tt.wantVendorAllowed, va, got.IsRangeEncoding, got.ConsentedVendors)
			}
			if pc := got.PublisherCC; pc != tt.publisherCountry {
				t.Errorf("publisherCountry failed. Expected %s, got %s", tt.publisherCountry, pc)
			}
		})
	}
}
